#! /bin/sh

#exec > /var/log/bspwmrc.log

#pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

#bspc monitor eDP-1-1 -d I II III IV V
#bspc monitor HDMI-0 -d VI VII VIII IX X

bspc monitor eDP-1-1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true
bspc config focus_follows_pointer      true
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config borderless_singleton       true
bspc config single_monocle             true
bspc config split_ratio                0.5

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

export XDG_CURRENT_DESKTOP="LXQt"
export XDG_SESSION_DESKTOP="LXQt"
export XDG_SESSION_TYPE="x11"
# This line is CRITICAL on Artix to ensure D-Bus session variables are updated
dbus-update-activation-environment --all

# disable sleep
xset s off -dpms

sudo light -S 15

# set cursor and others
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

# notifications"
dunst &
sh "/usr/bin/FanNotifications/fan-boost-notification/FanNotifications.sh" &
#dunst & sh "/usr/bin/FanNotifications/fan-boost-notification/FanNotifications.sh &

#gentoo-pipewire-launcher &

# set wallpaper
xwallpaper --zoom "/home/szyme/Pictures/ArchLinux_Synthwave_4K_Wallpaper.png"

clipcatd

#picom -b --no-vsync --no-fading-openclose
fastcompmgr &

# statusbar
bash ~/.config/bspwm/bar.sh &
bspc config top_padding 16
