#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio                0.5
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true
bspc config focus_follows_pointer      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# disable sleep
xset s off -dpms

# set cursor and others
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

# notifications
dunst &

# statusbar
#bspc config top_padding 32

#gentoo-pipewire-launcher &

# set wallpaper
xwallpaper --zoom "/home/szyme/Pictures/ArchLinux_Synthwave_4K_Wallpaper.png"

picom -b --no-vsync --no-fading-openclose
